CREATE TABLE AUTHOR ( ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL
)

CREATE TABLE BOOKS ( ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PRICE DOUBLE NOT NULL,
    AUTHOR_ID INT NOT NULL,
    FOREIGN KEY ( AUTHOR_ID ) REFERENCES AUTHOR(ID)
)


SELECT * FROM my_db.AUTHOR , my_db.BOOKS

SELECT my_db.BOOKS.*, my_db.AUTHOR.FIRST_NAME FROM my_db.BOOKS, my_db.AUTHOR where my_db.BOOKS.AUTHOR_ID = my_db.AUTHOR.ID ## AND my_db.AUTHOR._ID = 1

SELECT * FROM my_db.BOOKS where my_db.BOOKS.AUTHOR_ID IN ( SELECT ID FROM my_db.AUTHOR WHERE ID = 2 ) 

SELECT * FROM my_db.books INNER JOIN my_db.author ON my_db.books.AUTHOR_ID = my_db.author.ID

## LEFT | RIGHT
